### PR TITLE
Remove obsolete docker-compose files in flowdb/ folder

### LINKED ISSUE #188: flowdb/docker-compose.yml file is obsolete
As far as I can tell the file `flowdb/docker-compose.yml` is obsolete (superseded by the toplevel docker-compose files) and should be removed.

### PR DESCRIPTION
**Pull request by maxalbert**
Closes #188 

### I have:

- [ ] Formatted any Python files with [black](https://github.com/ambv/black)
- [X] Brought the branch up to date with master
- [X] Added any relevant Github labels
- [ ] Added tests for any new additions
- [ ] Added or updated any relevant documentation
- [ ] Added an Architectural Decision Record (ADR), if appropriate
- [ ] Added an [MPLv2 License Header](https://www.mozilla.org/en-US/MPL/headers/) if appropriate

### CODE REVIEW

**Comment by josh-gree** [comment]
Do we have a way of attaching PGhero still?

**Comment by maxalbert** [comment]
If we want this it should be added to the toplevel `docker-compose-dev.yml` file. Sounds like it's a little hypothetical at this stage? So I'd probably wait until we actually have a use case (otherwise it lingers in there unmaintained), but in principle it would just be another service in there.

**Comment by maxalbert** [comment]
Also you can just spin it up manually via `docker run`?

**Comment by maxalbert** [comment]
Well the obsolete`docker-compose.pghero.yml` doesn't contain anything special at all so I presume it comes with that capability out of the box (but haven't worked with it so can't say for sure).

**Pull request merged**
