### PR TITLE
Updating demo_scopes.json

### LINKED ISSUE #5735: FlowclientConnectionError: User claims verification failed
**Description**
Getting FlowclientConnectionError although I have followed the setup instructions and generated a token.

**Where the error occurs**
When trying to run the worked example at `run_query`:
```
fc.run_query(
        connection=conn,
        query_spec=fc.aggregates.spatial_aggregate_spec(
            locations=query_spec
        ),  # Wrap the query spec in a spatial aggregate query, so that we are allowed to get the result
    )
    for period, query_spec in home_locations_specs.items()
```
the error is produced. It is a {401 or 403} error.

**Version**
flowclient 1.17.1

**Steps**
I have run the docker environments and logged into FlowAuth. It also allowed me to generate my token, which works when doing other flowclient functions (e.g. `fc.connect` and `fc.get_available_dates`). But I get the FlowclientConnectionError for `fc.run_query` 

**Error message**
```
---------------------------------------------------------------------------
FlowclientConnectionError                 Traceback (most recent call last)
Input In [51], in <cell line: 3>()
      1 # Run spatial aggregates of the home locations queries
----> 3 home_locations_ids = {
      4     period: fc.run_query(
      5         connection=conn,
      6         query_spec=fc.aggregates.spatial_aggregate_spec(
      7             locations=query_spec
      8         ),  # Wrap the query spec in a spatial aggregate query, so that we are allowed to get the result
      9     )
     10     for period, query_spec in home_locations_specs.items()  # Loop over the three query specifications and run them all
     11 }
     13 home_locations_ids

Input In [51], in <dictcomp>(.0)
      1 # Run spatial aggregates of the home locations queries
      3 home_locations_ids = {
----> 4     period: fc.run_query(
      5         connection=conn,
      6         query_spec=fc.aggregates.spatial_aggregate_spec(
      7             locations=query_spec
      8         ),  # Wrap the query spec in a spatial aggregate query, so that we are allowed to get the result
      9     )
     10     for period, query_spec in home_locations_specs.items()  # Loop over the three query specifications and run them all
     11 }
     13 home_locations_ids

File /opt/conda/lib/python3.10/site-packages/flowclient/client.py:523, in run_query(connection, query_spec)
    505 """
    506 Run a query of a specified kind with parameters and get the identifier for it.
    507 
   (...)
    518     Identifier of the query
    519 """
    520 logger.info(
    521     f"Requesting run of {query_spec} at {connection.url}/api/{connection.api_version}"
    522 )
--> 523 r = connection.post_json(route="run", data=query_spec)
    524 if r.status_code == 202:
    525     query_id = r.headers["Location"].split("/").pop()

File /opt/conda/lib/python3.10/site-packages/flowclient/connection.py:192, in Connection.post_json(self, route, data)
    190     except ValueError:
    191         error_msg = "Unknown access denied error"
--> 192     raise FlowclientConnectionError(error_msg)
    193 else:
    194     print("******************")

FlowclientConnectionError: User claims verification failed
```

### PR DESCRIPTION
**Pull request by Thingus**
Closes #5735 

### I have:

- [x] Formatted any Python files with [black](https://github.com/ambv/black)
- [x] Brought the branch up to date with master
- [x] Added any relevant Github labels
- [x] Added tests for any new additions
- [x] Added or updated any relevant documentation
- [ ] Added an Architectural Decision Record (ADR), if appropriate
- [ ] Added an [MPLv2 License Header](https://www.mozilla.org/en-US/MPL/headers/) if appropriate
- [x] Updated the [Changelog](https://github.com/Flowminder/FlowKit/blob/master/CHANGELOG.md) 

### Description

Updates Flowauth quickstart to work with worked examples

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203640272340521

### CODE REVIEW

**Comment by Thingus** [comment]
I think that just adding the `admin3` scopes to the default role should be enough to make all the worked examples workable - @jc-harrison can you confirm?

**Comment by jc-harrison** [comment]
> I think that just adding the `admin3` scopes to the default role should be enough to make all the worked examples workable - @jc-harrison can you confirm?

I think `admin3` is all that's needed for the worked examples, but I think I'd argue for enabling all queries in the demo roles - the main purpose of the quick-start is to enable people to try running FlowKit queries, so I think it's good if users can modify the queries as they like and still be able to run them without needing to understand how to enter FlowAuth admin mode and enable more scopes.

**Comment by jc-harrison** [comment]
Linking [this issue](https://github.com/Flowminder/FlowKit/issues/4386) here for visibility - at some point it would be good to modify the quick-start so that FlowAuth demo data is populated from the quick-started FlowAPI spec, rather than from a hard-coded pre-defined spec.

**Comment by Thingus** [comment]
> 

I'm inclined to agree there - I think that when an org gets into the situation that they'll be needing the finer-grained auth tools, they're probably past the quickstart. Will update.

**Pull request merged**
